### model
model_name_or_path: Qwen/Qwen3-VL-4B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true
use_lidar_modality: true
use_lidar_object_features: true
use_lidar_object_geometry_features: false
use_lidar_object_numeric_features: false
use_lidar_scene_features: true
use_lidar_template_router: true
lidar_encoder_mode: projection_only
lidar_scene_memory_mode: direct
lidar_hidden_size: 512
lidar_object_prefix_length: 16
lidar_object_token_dim: 523
lidar_object_geometry_token_dim: 128
lidar_object_numeric_token_dim: 13
lidar_object_numeric_label_vocab_size: 16
lidar_object_numeric_label_emb_dim: 32
lidar_scene_token_dim: 386
lidar_scene_token_length: 256
lidar_scene_memory_length: 64
lidar_cross_attention_heads: 8
lidar_decoder_adapter_layers: 4
lidar_decoder_adapter_heads: 8
lidar_decoder_adapter_gate_bias: -5.0
lidar_template_router_output_dim: 3
lidar_gate_usage_weight: 0.003

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
additional_target: lidar_object_encoder,lidar_scene_encoder,lidar_object_connector,lidar_scene_direct_proj,lidar_decoder_adapter_blocks.0,lidar_decoder_adapter_blocks.1,lidar_decoder_adapter_blocks.2,lidar_decoder_adapter_blocks.3,lidar_template_router

### dataset
dataset_dir: data/interGeo_vqa_v5_lidar
dataset: interGeo_vqa_v5_lidar_train
eval_dataset: interGeo_vqa_v5_lidar_val
template: qwen3_vl_nothink
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/InterGeo-qwen3vl_4b/v5/train
logging_steps: 20
save_steps: 500
save_total_limit: 2
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
ddp_find_unused_parameters: false
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
