### model
model_name_or_path: llava-hf/llama3-llava-next-8b-hf
image_max_pixels: 196608

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset_dir: data/intersection_vqa
dataset: intersection_vqa_train
eval_dataset: intersection_vqa_val
template: llava_next_llama3
cutoff_len: 8192
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/intersection_llava_next_llama3_8b/lora/sft
logging_steps: 100
save_steps: 500
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
max_steps: 1500
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
